name: Build

on:
  pull_request:
    branches: [ build ]
  push:
    branches: [ build ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print Hell
        run: echo "Hello, GitHub!"

